Feat/setup front end project
EtienneDx/git-mentor pull request #15
Opened 2023-12-18 09:35 UTC by Marin-de-Drouas

Basic front setup #4 :

React app in typescript.
Current added libs:
- react-router-dom
- axios
- styled components
- fontawesome

/!\ Check the CI carefully
Bonus: Email Password auth from #10

2023-12-18 12:21 UTC, EtienneDx reviewed
Overall nice, I've got a couple things I'm not 100% behind here but looks good. I usually try to use some kind of component library to make faster UI, here we're doing it by hand right?

2023-12-18 12:50 UTC, Marin-de-Drouas commented on mentor-app/public/favicon.ico
Yes indeed

2023-12-18 13:13 UTC, Marin-de-Drouas commented on mentor-app/src/App.test.tsx
> +});
Yes i'll correct that

2023-12-18 13:13 UTC, Marin-de-Drouas commented on mentor-app/src/setupTests.ts
For some reason moving this file break everything

2023-12-19 14:23 UTC, EtienneDx reviewed
Couple small comments, nice work :)

2023-12-19 14:23 UTC, EtienneDx commented on gmt-web-app/package.json
The rest of the project is setup with 2 spaces. For consistency, I think we should keep it to 2 spaces here too

2023-12-19 14:23 UTC, EtienneDx commented on gmt-web-app/.prettierrc
> +    "tabWidth": 4,
```suggestion
    "tabWidth": 2,
```
See other comment

2023-12-19 14:23 UTC, EtienneDx commented on gmt-web-app/src/features/auth/components/AuthenticationForm.tsx
> +        useAuthentication();
Nice, this looks cool!

2023-12-19 14:23 UTC, EtienneDx commented on gmt-web-app/src/features/auth/hooks/useAuthentication.tsx
> +}
These will probably be replaced when protobuf is added

2023-12-19 16:40 UTC, EtienneDx requested changes
Nice, code looks good, I've still got a couple concerns, mostly around the docs and ci. As we plan for the project to get increasingly complex, I'm afraid we'd get lost in the complexity otherwise.

(eg. I'm not sure which libs are used and having some reference list would allow me to skip reading all the code and find what I'm looking for faster)

2023-12-19 16:40 UTC, EtienneDx commented on gmt-web-app/.eslintrc
> +        "max-lines": ["error", { "max": 200, "skipBlankLines": true }],
Does that mean 200 lines per file? seems a little low doesn't it? Altough maybe for front end it makes sense idk?

2023-12-19 16:40 UTC, EtienneDx commented on gmt-web-app/README.md
> +## Available Scripts
Would be nice to add the lint and format scripts here

2023-12-19 16:40 UTC, EtienneDx commented on .github/workflows/react-unit-test.yml
> +        run: npm run format
Format modifies the code, here we can only run checks, so we need another script.

```suggestion
        run: npm run format:check
```

2023-12-19 16:40 UTC, EtienneDx commented on gmt-web-app/package.json
> +        "format": "prettier . --write"
As mentionned above, we need a check and a write version for both of these. (write for lint is just bonus but I like to have it)

Something like:
```suggestion
        "lint": "eslint . --ext .ts,.tsx",
        "lint:fix": "eslint . --ext .ts,.tsx --fix",
        "format": "prettier . --write",
        "format:check": "prettier ."
```

2023-12-19 16:40 UTC, EtienneDx commented on gmt-web-app/README.md
> +You don’t have to ever use `eject`. The curated feature set is suitable for small and middle deployments, and you shouldn’t feel obligated to use this feature. However we understand that this tool wo
We can remove this part, we shouldn't ever need to use this so that just adds noise

2023-12-19 16:40 UTC, EtienneDx commented on gmt-web-app/README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
We don't care about this, but it would be nice to have a brief description of what the project is and how it will be served. Would be even better with a quick reference to all libraries we're using and a brief explainer on why we don't use other such as Next.js

2023-12-20 10:24 UTC, Lerri-Cofannos commented on gmt-web-app/.prettierrc
> +    "tabWidth": 4,
I'm used to 4, but for consistency's sake, okay...

2023-12-20 10:25 UTC, Lerri-Cofannos commented on gmt-web-app/src/features/auth/hooks/useAuthentication.tsx
> +}
I haven't upgraded the authentication feature, I just did some refactoring on it. I believe that they should be migrated to a `types.ts` file at some point

2023-12-20 10:30 UTC, Lerri-Cofannos commented on gmt-web-app/.eslintrc
> +        "max-lines": ["error", { "max": 200, "skipBlankLines": true }],
This is a config I used on another project, and it works great! The 200 lines limit is to encourage splitting files into readable size. This should be done by using hooks and components. [See atomic design](https://medium.com/@janelle.wg/atomic-design-pattern-how-to-structure-your-react-application-2bb4d9ca5f97)

2023-12-20 10:40 UTC, EtienneDx commented on gmt-web-app/src/features/auth/hooks/useAuthentication.tsx
> +}
With the protobuf, we'll have the types defined automatically (generated), just wrote this as a memo

2023-12-20 10:41 UTC, EtienneDx commented on gmt-web-app/.eslintrc
> +        "max-lines": ["error", { "max": 200, "skipBlankLines": true }],
Works for me. I'm just considering the rust projects I worked on, on which all files were at least 500 lines (back-end in rust can get a bit verbose)

2023-12-20 10:55 UTC, Lerri-Cofannos commented on gmt-web-app/README.md
> +## Available Scripts
Done 👍

2023-12-20 10:57 UTC, EtienneDx approved these changes
LGTM! Let's merge it!

2023-12-20 10:58 UTC, merged