Feat/data visualisation 1
EtienneDx/git-mentor pull request #23
Opened 2023-12-21 13:56 UTC by Lerri-Cofannos

- Create pages meant for database visualisation
- Create a table component
- Setup routing

2024-04-30 22:44 UTC, EtienneDx requested changes
Sorry to be a pain :/ I think you misunderstood a bit the sdk stuff. The goal is to abstract all the network calls and types definitions, and I think here you took the generated code and refactored it. The idea of it is more of a black box with some APIs.

2024-04-30 22:44 UTC, EtienneDx commented on gmt-web-app/src/context/api.tsx
> +import { main_service } from "./services";
That appears to be an error, the services directory doesn't really exist: the sdk to access the APIs is auto-generated

2024-04-30 22:44 UTC, EtienneDx commented on gmt-web-app/src/context/services.ts
Did you refactor the generated files? This looks autogenerated :/

2024-04-30 22:44 UTC, EtienneDx commented on gmt-web-app/src/context/types.ts
idem

2024-04-30 22:44 UTC, EtienneDx commented on gmt-web-app/src/helpers/types.ts
These types will be generated from the back-end too. Since the APIs haven't been built yet, they aren't but they will be. In the meantime they can serve as placeholders

2024-04-30 22:46 UTC, EtienneDx commented on gmt-web-app/src/context/services.ts
> +    }
Missed that, but the token isn't always required: authentication endpoints do not require it.

2024-05-01 13:20 UTC, Lerri-Cofannos commented on gmt-web-app/src/context/api.tsx
> +import { main_service } from "./services";
[243a756](https://github.com/EtienneDx/git-mentor/pull/23/commits/243a75679537be3a49edbde367d3f57846bb036f)

2024-05-01 13:21 UTC, Lerri-Cofannos commented on gmt-web-app/src/context/services.ts
Nope I hadn't
[243a756](https://github.com/EtienneDx/git-mentor/pull/23/commits/243a75679537be3a49edbde367d3f57846bb036f)

2024-05-01 13:23 UTC, Lerri-Cofannos commented on gmt-web-app/src/context/services.ts
> +    }
[243a756](https://github.com/EtienneDx/git-mentor/pull/23/commits/243a75679537be3a49edbde367d3f57846bb036f)

2024-05-01 20:32 UTC, EtienneDx approved these changes
LGTM, kind of a huge PR so difficult to make sure I reviewed everything correctly. I haven't launched locally yet so I haven't seen the design, I trust you on this.

I'm creating a new issue to have a proper CI pipeline deploying this for easier review of front changes.

2024-05-01 20:33 UTC, EtienneDx commented
PS: don't forget to squash when merging :)

2024-05-03 15:21 UTC, merged