docs: Added and updated readmes across the project
EtienneDx/git-mentor pull request #37
Opened 2024-04-25 20:57 UTC by EtienneDx

Project was drastically missing documentation. This aims to help.

2024-04-26 17:45 UTC, Lerri-Cofannos requested changes
Great documentation ! A few questions left to be answered, some details to be looked into, and couple of features that could make it glow up

2024-04-26 17:45 UTC, Lerri-Cofannos commented on README.md
> +The front-end uses Node.js. To install Node.js, follow the instructions at [https://nodejs.org/en/download/](https://nodejs.org/en/download/). As of the 25/04/2024, the project uses v20.10
```suggestion
The frontend uses Node.js. To install Node.js, follow the instructions at [https://nodejs.org/en/download/](https://nodejs.org/en/download/). As of the 25/04/2024, the project uses v20.10
```
front-end is a compound adjective 😇 [ref](https://medium.com/@ist.stevkovski/is-it-front-end-or-front-end-or-frontend-3ae717cae4aa). I suggest frontend or front end

2024-04-26 17:45 UTC, Lerri-Cofannos commented on README.md
> +Otherwise, you would need to modify the environments of the project consuming the database. The database is a Postgre-SQL db.
```suggestion
Otherwise, you would need to modify the environments of the project consuming the database. The database is a [Postgre-SQL](https://www.postgresql.org/) system.
```

2024-04-26 17:45 UTC, Lerri-Cofannos commented on README.md
> +The front-end uses npm:
same suggestion as above (there are a few other instances of it, but I leave it to you to find them)
```suggestion
The frontend uses npm:
```

2024-04-26 17:45 UTC, Lerri-Cofannos commented on README.md
> +*/!\* the front-end requires a more complex setup to run properly, see the [gmt-web-app](./gmt-web-app/) documentation for more information on how to generate the APIs SDK.
This might lead to confusion. I would phrase it like such: "for the front end, go see the documentation, else use cargo run"

2024-04-26 17:45 UTC, Lerri-Cofannos commented on README.md
I guess this would be the file where we expect to see the badges of the repo (nb of contributors, build status, ci status, last update, etc), a logo and maybe the intent of the project. What do you think?

2024-04-26 17:45 UTC, Lerri-Cofannos commented on gmt-web-app/README.md
> +Generates the SDK from the OpenAPI spec file. The SDK is generated in the `src/gmt-api` folder. This script requires the (gmt-api)[../gmt-api] project to be built.
How could I use this?

2024-04-30 18:24 UTC, EtienneDx commented
@Lerri-Cofannos Resolved all comments, ready to merge

2024-04-30 20:17 UTC, Lerri-Cofannos approved these changes
Nicely done!

2024-04-30 20:17 UTC, merged